In [1]:
import xarray as xr
from pathlib import Path

In [2]:
project_dir = Path("/Users/jlee/Desktop/github/AS_rainfall")
for file in project_dir.glob("raw_data/climate_variables_daily_concatenated/*.nc"):
    ds = xr.open_dataset(file)
    print(ds)

<xarray.Dataset> Size: 49MB
Dimensions:         (valid_time: 1827, pressure_level: 2, latitude: 41,
                     longitude: 81)
Coordinates:
    number          int64 8B ...
  * pressure_level  (pressure_level) float64 16B 925.0 750.0
  * latitude        (latitude) float64 328B -10.0 -10.25 -10.5 ... -19.75 -20.0
  * longitude       (longitude) float64 648B -180.0 -179.8 ... -160.2 -160.0
  * valid_time      (valid_time) datetime64[ns] 15kB 1980-01-01 ... 1984-12-31
Data variables:
    v               (valid_time, pressure_level, latitude, longitude) float32 49MB ...
Attributes:
    GRIB_centre:             ecmf
    GRIB_centreDescription:  European Centre for Medium-Range Weather Forecasts
    GRIB_subCentre:          0
    Conventions:             CF-1.7
    institution:             European Centre for Medium-Range Weather Forecasts
    history:                 2025-09-20T03:10 GRIB to CDM+CF via cfgrib-0.9.1...
<xarray.Dataset> Size: 24MB
Dimensions:     (valid_time: 1827, l

In [3]:
ds = xr.open_dataset("/Users/jlee/Desktop/github/AS_rainfall/raw_data/climate_variables_daily/gh_1980-1984/geopotential_1980_01_full.nc")
print(ds)

<xarray.Dataset> Size: 65MB
Dimensions:         (valid_time: 31, pressure_level: 2, latitude: 181,
                     longitude: 1440)
Coordinates:
    number          int64 8B ...
  * pressure_level  (pressure_level) float64 16B 1e+03 500.0
  * latitude        (latitude) float64 1kB 25.0 24.75 24.5 ... -19.75 -20.0
  * longitude       (longitude) float64 12kB -180.0 -179.8 ... 179.5 179.8
  * valid_time      (valid_time) datetime64[ns] 248B 1980-01-01 ... 1980-01-31
Data variables:
    z               (valid_time, pressure_level, latitude, longitude) float32 65MB ...
Attributes:
    GRIB_centre:             ecmf
    GRIB_centreDescription:  European Centre for Medium-Range Weather Forecasts
    GRIB_subCentre:          0
    Conventions:             CF-1.7
    institution:             European Centre for Medium-Range Weather Forecasts
    history:                 2025-09-20T02:59 GRIB to CDM+CF via cfgrib-0.9.1...


In [4]:
# Open daily features NPZ file
import numpy as np

npz_path = Path(project_dir / "output/daily_features.npz")
data = np.load(npz_path, allow_pickle=True)

# Access the 'variables' array
variables = data['variables']
print("Variables:", variables)
print("-" * 20)

# Access the 'meta' array (station and date info)
meta = data['meta']
print("Shape of meta array:", meta.shape)
print("First meta entry:", meta[0])
print("-" * 20)

# Access the 'patches' array
patches = data['patches']
print("Shape of patches array:", patches.shape)
print("(Samples, Variables, Height, Width)")
print("-" * 20)

# Print the patch for the first sample, first variable
print("First patch (for variable '{}' at '{}' for station '{}'):".format(
    variables[0], meta[0]['date'], meta[0]['station']
))
print(patches[0, 0, :, :])

Variables: ['t2m' 't' 'z' 'w' 'pt' 'tcwv' 'q' 'skt' 'msl' 'u' 'v']
--------------------
Shape of meta array: (47502,)
First meta entry: {'station': 'poloa_UH', 'date': '1980-01-01'}
--------------------
Shape of patches array: (47502, 11, 3, 3)
(Samples, Variables, Height, Width)
--------------------
First patch (for variable 't2m' at '1980-01-01' for station 'poloa_UH'):
[[0.9311748  0.98096097 0.91522586]
 [0.92175585 0.9881637  0.96315193]
 [0.8911639  0.9609357  0.9669512 ]]


In [5]:
npz_path = "/Users/jlee/Desktop/github/AS_rainfall/ML_Data_Preprocessing/output/reanalysis_npz_1/reanalysis_features_all_standardized.npz"

npz = np.load(npz_path, allow_pickle=True)
print(npz.files)
# ['patches', 'stations', 'years', 'months', 'variables', 'patch_size']

for i in range(len(npz.files)):
  print(npz.files[i])
  print(npz[npz.files[i]].shape)

print("\nExample patches for single station-date")
print(npz['patches'][0,1,:,:])
print(npz['patches'][0,2,:,:])
print(npz['patches'][0,3,:,:])
print(npz['patches'][0,4,:,:])

print("\nExample patches for single variable")
print(npz['patches'][0,1,:,:])
print(npz['patches'][100,1,:,:])
print(npz['patches'][200,1,:,:])
print(npz['patches'][300,1,:,:])
print(npz['patches'][400,1,:,:])



['patches', 'stations', 'years', 'months', 'variables', 'patch_size']
patches
(2032, 16, 3, 3)
stations
(2032,)
years
(2032,)
months
(2032,)
variables
(16,)
patch_size
()

Example patches for single station-date
[[ 0.00459562  0.18382493  0.11737075]
 [-0.52940845 -0.23740405 -0.37906596]
 [-1.4305518  -1.1327846  -1.1993117 ]]
[[-0.27448347 -0.16603096 -0.05956833]
 [ 0.17723659  0.2647943   0.4205082 ]
 [ 0.8538208   0.9602834   1.1463442 ]]
[[ 0.39638704  0.42722794  0.4171641 ]
 [ 0.22010681  0.24624044  0.25967246]
 [-0.4594892  -0.42933813 -0.3790593 ]]
[[-0.52667403 -0.9080434  -1.148746  ]
 [-0.22913912 -0.25974143 -0.22836769]
 [ 0.1535158   0.511998    0.87510884]]

Example patches for single variable
[[ 0.00459562  0.18382493  0.11737075]
 [-0.52940845 -0.23740405 -0.37906596]
 [-1.4305518  -1.1327846  -1.1993117 ]]
[[-1.2608055 -1.1851237 -1.3036981]
 [-1.3564018 -1.217986  -1.4270868]
 [-1.7947001 -1.6592022 -1.8524008]]
[[-0.2547653  -0.15734538 -0.18050586]
 [-0.49855214

In [6]:
npz_path = "/Users/jlee/Desktop/github/AS_rainfall/ML_Data_Preprocessing/output/reanalysis_npz/reanalysis_features_all_standardized.npz"
npz = np.load(npz_path, allow_pickle=True)
print(npz.files)

for i in range(len(npz.files)):
  print(npz.files[i])
  print(npz[npz.files[i]].shape)

print("\nExample patches for single station-date")
print(npz['patches'][0,1,:,:])
print(npz['patches'][0,2,:,:])
print(npz['patches'][0,3,:,:])
print(npz['patches'][0,4,:,:])

print("\nExample patches for single variable")
print(npz['patches'][0,1,:,:])
print(npz['patches'][1000,1,:,:])
print(npz['patches'][2000,1,:,:])
print(npz['patches'][3000,1,:,:])
print(npz['patches'][4000,1,:,:])


['patches', 'stations', 'years', 'months', 'variables', 'patch_size', 'days']
patches
(6930, 16, 3, 3)
stations
(6930,)
years
(6930,)
months
(6930,)
variables
(16,)
patch_size
()
days
(6930,)

Example patches for single station-date
[[-0.13121377 -0.17199641 -0.18480256]
 [-0.47134504 -0.43312362 -0.40904808]
 [-0.626989   -0.49711496 -0.47039938]]
[[-1.9160074 -1.9256539 -1.9195223]
 [-1.8864013 -1.8914297 -1.8919429]
 [-1.8587705 -1.8604892 -1.8694943]]
[[-2.5143805 -2.5652163 -2.6139004]
 [-2.5527446 -2.6036038 -2.6556199]
 [-2.5938392 -2.6465495 -2.6998613]]
[[0.43209323 0.3644573  0.35401276]
 [0.6075209  0.5275137  0.49972922]
 [0.74907976 0.72981316 0.67698205]]

Example patches for single variable
[[-0.13121377 -0.17199641 -0.18480256]
 [-0.47134504 -0.43312362 -0.40904808]
 [-0.626989   -0.49711496 -0.47039938]]
[[-0.35936022 -0.58758545 -0.77167875]
 [-0.7864945  -0.94454205 -0.9962395 ]
 [-1.1329304  -1.0581424  -1.0493948 ]]
[[-0.97665596 -0.9782321  -0.8726306 ]
 [-1.11062