In [1]:
import xarray as xr
from pathlib import Path
import numpy as np

In [42]:
project_dir = Path("/Users/jlee/Desktop/github/AS_rainfall")
for file in project_dir.glob("raw_data/climate_variables_daily_concatenated/*.nc"):
    print(file)
    ds = xr.open_dataset(file)
    print(ds)

/Users/jlee/Desktop/github/AS_rainfall/raw_data/climate_variables_daily_concatenated/vwnd.day.mean.nc
<xarray.Dataset> Size: 49MB
Dimensions:         (valid_time: 1827, pressure_level: 2, latitude: 41,
                     longitude: 81)
Coordinates:
    number          int64 8B ...
  * pressure_level  (pressure_level) float64 16B 925.0 750.0
  * latitude        (latitude) float64 328B -10.0 -10.25 -10.5 ... -19.75 -20.0
  * longitude       (longitude) float64 648B -180.0 -179.8 ... -160.2 -160.0
  * valid_time      (valid_time) datetime64[ns] 15kB 1980-01-01 ... 1984-12-31
Data variables:
    v               (valid_time, pressure_level, latitude, longitude) float32 49MB ...
Attributes:
    GRIB_centre:             ecmf
    GRIB_centreDescription:  European Centre for Medium-Range Weather Forecasts
    GRIB_subCentre:          0
    Conventions:             CF-1.7
    institution:             European Centre for Medium-Range Weather Forecasts
    history:                 2025-09-20T03:

In [12]:
project_dir = Path("/Users/jlee/Desktop/github/AS_rainfall")
for file in project_dir.glob("raw_data/climate_variables_daily_raw/gh_1980-1984/*.nc"):
    print(file)
    with xr.open_dataset(file) as ds:
        subset = ds.sel(latitude=slice(-10, -20), longitude=slice(-180, -160))
        print(subset)

/Users/jlee/Desktop/github/AS_rainfall/raw_data/climate_variables_daily_raw/gh_1980-1984/geopotential_1983_09_full.nc
<xarray.Dataset> Size: 798kB
Dimensions:         (valid_time: 30, pressure_level: 2, latitude: 41,
                     longitude: 81)
Coordinates:
    number          int64 8B ...
  * pressure_level  (pressure_level) float64 16B 1e+03 500.0
  * latitude        (latitude) float64 328B -10.0 -10.25 -10.5 ... -19.75 -20.0
  * longitude       (longitude) float64 648B -180.0 -179.8 ... -160.2 -160.0
  * valid_time      (valid_time) datetime64[ns] 240B 1983-09-01 ... 1983-09-30
Data variables:
    z               (valid_time, pressure_level, latitude, longitude) float32 797kB ...
Attributes:
    GRIB_centre:             ecmf
    GRIB_centreDescription:  European Centre for Medium-Range Weather Forecasts
    GRIB_subCentre:          0
    Conventions:             CF-1.7
    institution:             European Centre for Medium-Range Weather Forecasts
    history:               

In [10]:
project_dir = Path("/Users/jlee/Desktop/github/AS_rainfall")
for file in project_dir.glob("raw_data/climate_variables_daily/*.nc"):
    print(file)
    ds = xr.open_dataset(file)
    print(ds)

/Users/jlee/Desktop/github/AS_rainfall/raw_data/climate_variables_daily/air.2m.day.mean.nc
<xarray.Dataset> Size: 24MB
Dimensions:     (valid_time: 1827, latitude: 41, longitude: 81)
Coordinates:
    number      int64 8B ...
  * latitude    (latitude) float64 328B -10.0 -10.25 -10.5 ... -19.75 -20.0
  * longitude   (longitude) float64 648B -180.0 -179.8 -179.5 ... -160.2 -160.0
  * valid_time  (valid_time) datetime64[ns] 15kB 1980-01-01 ... 1984-12-31
Data variables:
    t2m         (valid_time, latitude, longitude) float32 24MB ...
Attributes:
    GRIB_centre:             ecmf
    GRIB_centreDescription:  European Centre for Medium-Range Weather Forecasts
    GRIB_subCentre:          0
    Conventions:             CF-1.7
    institution:             European Centre for Medium-Range Weather Forecasts
    history:                 2025-09-26T01:29 GRIB to CDM+CF via cfgrib-0.9.1...
/Users/jlee/Desktop/github/AS_rainfall/raw_data/climate_variables_daily/omega.day.mean.nc
<xarray.Dataset> 

In [47]:
project_dir = Path("/Users/jlee/Desktop/github/AS_rainfall")
for file in project_dir.glob("raw_data/climate_variables_monthly/*.nc"):
    print(file)
    ds = xr.open_dataset(file)
    print(ds)

/Users/jlee/Desktop/github/AS_rainfall/raw_data/climate_variables_monthly/air.2m.mon.mean.nc
<xarray.Dataset> Size: 67MB
Dimensions:  (time: 926, lat: 94, lon: 192)
Coordinates:
  * lat      (lat) float32 376B 88.54 86.65 84.75 82.85 ... -84.75 -86.65 -88.54
  * lon      (lon) float32 768B 0.0 1.875 3.75 5.625 ... 352.5 354.4 356.2 358.1
  * time     (time) datetime64[ns] 7kB 1948-01-01 1948-02-01 ... 2025-02-01
Data variables:
    air      (time, lat, lon) float32 67MB ...
Attributes:
    Conventions:    COARDS
    description:    Data is from NMC initialized reanalysis\n(4x/day).  It co...
    platform:       Model
    NCO:            20121012
    history:        created 97/10/04 by Hoop (netCDF2.3)\nConverted to chunke...
    title:          monthly mean air.2m from the NCEP Reanalysis
    dataset_title:  NCEP-NCAR Reanalysis 1
    References:     http://www.psl.noaa.gov/data/gridded/data.ncep.reanalysis...
/Users/jlee/Desktop/github/AS_rainfall/raw_data/climate_variables_monthly/vw

In [44]:
ds = xr.open_dataset("/Users/jlee/Desktop/github/AS_rainfall/raw_data/climate_variables_daily/gh_1980-1984/geopotential_1980_01_full.nc")
print(ds)
print(ds.data_vars)

<xarray.Dataset> Size: 65MB
Dimensions:         (valid_time: 31, pressure_level: 2, latitude: 181,
                     longitude: 1440)
Coordinates:
    number          int64 8B ...
  * pressure_level  (pressure_level) float64 16B 1e+03 500.0
  * latitude        (latitude) float64 1kB 25.0 24.75 24.5 ... -19.75 -20.0
  * longitude       (longitude) float64 12kB -180.0 -179.8 ... 179.5 179.8
  * valid_time      (valid_time) datetime64[ns] 248B 1980-01-01 ... 1980-01-31
Data variables:
    z               (valid_time, pressure_level, latitude, longitude) float32 65MB ...
Attributes:
    GRIB_centre:             ecmf
    GRIB_centreDescription:  European Centre for Medium-Range Weather Forecasts
    GRIB_subCentre:          0
    Conventions:             CF-1.7
    institution:             European Centre for Medium-Range Weather Forecasts
    history:                 2025-09-20T02:59 GRIB to CDM+CF via cfgrib-0.9.1...
Data variables:
    z        (valid_time, pressure_level, latitude, l

In [45]:
ds = xr.open_dataset("/Users/jlee/Desktop/github/AS_rainfall/raw_data/climate_variables_monthly/air.2m.mon.mean.nc")
print(ds)
print(ds.data_vars)

<xarray.Dataset> Size: 67MB
Dimensions:  (time: 926, lat: 94, lon: 192)
Coordinates:
  * lat      (lat) float32 376B 88.54 86.65 84.75 82.85 ... -84.75 -86.65 -88.54
  * lon      (lon) float32 768B 0.0 1.875 3.75 5.625 ... 352.5 354.4 356.2 358.1
  * time     (time) datetime64[ns] 7kB 1948-01-01 1948-02-01 ... 2025-02-01
Data variables:
    air      (time, lat, lon) float32 67MB ...
Attributes:
    Conventions:    COARDS
    description:    Data is from NMC initialized reanalysis\n(4x/day).  It co...
    platform:       Model
    NCO:            20121012
    history:        created 97/10/04 by Hoop (netCDF2.3)\nConverted to chunke...
    title:          monthly mean air.2m from the NCEP Reanalysis
    dataset_title:  NCEP-NCAR Reanalysis 1
    References:     http://www.psl.noaa.gov/data/gridded/data.ncep.reanalysis...
Data variables:
    air      (time, lat, lon) float32 67MB ...


In [4]:
# Open daily features NPZ file
import numpy as np

npz_path = Path(project_dir / "output/daily_features.npz")
data = np.load(npz_path, allow_pickle=True)

# Access the 'variables' array
variables = data['variables']
print("Variables:", variables)
print("-" * 20)

# Access the 'meta' array (station and date info)
meta = data['meta']
print("Shape of meta array:", meta.shape)
print("First meta entry:", meta[0])
print("-" * 20)

# Access the 'patches' array
patches = data['patches']
print("Shape of patches array:", patches.shape)
print("(Samples, Variables, Height, Width)")
print("-" * 20)

# Print the patch for the first sample, first variable
print("First patch (for variable '{}' at '{}' for station '{}'):".format(
    variables[0], meta[0]['date'], meta[0]['station']
))
print(patches[0, 0, :, :])

Variables: ['t2m' 't' 'z' 'w' 'pt' 'tcwv' 'q' 'skt' 'msl' 'u' 'v']
--------------------
Shape of meta array: (47502,)
First meta entry: {'station': 'poloa_UH', 'date': '1980-01-01'}
--------------------
Shape of patches array: (47502, 11, 3, 3)
(Samples, Variables, Height, Width)
--------------------
First patch (for variable 't2m' at '1980-01-01' for station 'poloa_UH'):
[[0.9311748  0.98096097 0.91522586]
 [0.92175585 0.9881637  0.96315193]
 [0.8911639  0.9609357  0.9669512 ]]


In [5]:
npz_path = "/Users/jlee/Desktop/github/AS_rainfall/ML_Data_Preprocessing/output/reanalysis_npz_1/reanalysis_features_all_standardized.npz"

npz = np.load(npz_path, allow_pickle=True)
print(npz.files)
# ['patches', 'stations', 'years', 'months', 'variables', 'patch_size']

for i in range(len(npz.files)):
  print(npz.files[i])
  print(npz[npz.files[i]].shape)

print("\nExample patches for single station-date")
print(npz['patches'][0,1,:,:])
print(npz['patches'][0,2,:,:])
print(npz['patches'][0,3,:,:])
print(npz['patches'][0,4,:,:])

print("\nExample patches for single variable")
print(npz['patches'][0,1,:,:])
print(npz['patches'][100,1,:,:])
print(npz['patches'][200,1,:,:])
print(npz['patches'][300,1,:,:])
print(npz['patches'][400,1,:,:])



FileNotFoundError: [Errno 2] No such file or directory: '/Users/jlee/Desktop/github/AS_rainfall/ML_Data_Preprocessing/output/reanalysis_npz_1/reanalysis_features_all_standardized.npz'

In [9]:
# npz_path = "/Users/jlee/Desktop/github/AS_rainfall/ML_Data_Preprocessing/output/reanalysis_npz/reanalysis_features_all_standardized.npz"
npz_path = "C:/Users/JR/Documents/GitHub/AS_rainfall/ML_Data_Preprocessing/output/reanalysis_npz/reanalysis_features_all_standardized_daily.npz"

npz = np.load(npz_path, allow_pickle=True)
print(npz.files)

for i in range(len(npz.files)):
  print(npz.files[i])
  print(npz[npz.files[i]].shape)

print("\nExample patches for single station-date")
print(npz['patches'][0,1,:,:])
print(npz['patches'][0,2,:,:])
print(npz['patches'][0,3,:,:])
print(npz['patches'][0,4,:,:])

print("\nExample patches for single variable")
print(npz['patches'][0,1,:,:])
print(npz['patches'][1000,1,:,:])
print(npz['patches'][2000,1,:,:])
print(npz['patches'][3000,1,:,:])
print(npz['patches'][4000,1,:,:])


['patches', 'stations', 'years', 'months', 'variables', 'patch_size', 'days']
patches
(11728, 15, 3, 3)
stations
(11728,)
years
(11728,)
months
(11728,)
variables
(15,)
patch_size
()
days
(11728,)

Example patches for single station-date
[[0.98337436 1.0331124  0.9674408 ]
 [0.97396445 1.0403082  1.0153205 ]
 [0.94340205 1.0131065  1.0191162 ]]
[[-1.407414  -1.4111654 -1.4047855]
 [-1.3896009 -1.3894477 -1.3848541]
 [-1.3733958 -1.3677303 -1.3653569]]
[[-0.44453147 -0.44415525 -0.44523695]
 [-0.42266235 -0.42165118 -0.42372054]
 [-0.40196896 -0.40133405 -0.40347394]]
[[-1.3267989  -1.1556698  -0.66535515]
 [-1.0723144  -0.9302468  -0.60438484]
 [-0.6346245  -0.49324423 -0.39035073]]

Example patches for single variable
[[0.98337436 1.0331124  0.9674408 ]
 [0.97396445 1.0403082  1.0153205 ]
 [0.94340205 1.0131065  1.0191162 ]]
[[-0.84222585 -0.8689926  -0.884175  ]
 [-0.7718888  -0.78339416 -0.8188197 ]
 [-0.5610358  -0.5541563  -0.64050597]]
[[-0.28071558 -0.31131753 -0.34958974]
 [-0.

In [39]:
npz_path = "/Users/jlee/Desktop/github/AS_rainfall/ML_Data_Preprocessing/output/reanalysis_npz_monthly_1/reanalysis_features_all_standardized.npz"
npz_old = np.load(npz_path, allow_pickle=True)
print(npz_old.files)

for i in range(len(npz_old.files)):
  print(npz_old.files[i])
  print(npz_old[npz_old.files[i]].shape)

print("\nExample patches for single station-date")
print("poloa_UH")
print(npz_old['patches'][npz_old['stations'] == 'poloa_UH'][0])
print("aasu_UH")
print(npz_old['patches'][npz_old['stations'] == 'aasu_UH'][0])

# print("\nExample patches for single variable")
# #find index of slp variable
# slp_bool_array = npz['variables'] == 'slp'
# slp_index = np.where(slp_bool_array)[0][0]
# print(npz['patches'][0][slp_index])
# print(npz['patches'][1][slp_index])


['patches', 'stations', 'years', 'months', 'variables', 'patch_size']
patches
(2032, 16, 3, 3)
stations
(2032,)
years
(2032,)
months
(2032,)
variables
(16,)
patch_size
()

Example patches for single station-date
poloa_UH
[[[-3.92072767e-01 -2.45166808e-01 -3.44171643e-01]
  [-9.91678059e-01 -7.36995995e-01 -7.72928894e-01]
  [-2.09587932e+00 -1.73260355e+00 -1.62003303e+00]]

 [[ 4.59562289e-03  1.83824927e-01  1.17370754e-01]
  [-5.29408455e-01 -2.37404048e-01 -3.79065961e-01]
  [-1.43055177e+00 -1.13278461e+00 -1.19931173e+00]]

 [[-2.74483472e-01 -1.66030958e-01 -5.95683344e-02]
  [ 1.77236587e-01  2.64794290e-01  4.20508206e-01]
  [ 8.53820801e-01  9.60283399e-01  1.14634418e+00]]

 [[ 3.96387041e-01  4.27227944e-01  4.17164087e-01]
  [ 2.20106810e-01  2.46240437e-01  2.59672463e-01]
  [-4.59489197e-01 -4.29338127e-01 -3.79059315e-01]]

 [[-5.26674032e-01 -9.08043385e-01 -1.14874601e+00]
  [-2.29139119e-01 -2.59741426e-01 -2.28367686e-01]
  [ 1.53515801e-01  5.11997998e-01  8.75108

In [5]:
# npz_path = "/Users/jlee/Desktop/github/AS_rainfall/ML_Data_Preprocessing/output/reanalysis_npz/reanalysis_features_all_standardized_daily.npz"
npz_path = "C:/Users/JR/Documents/GitHub/AS_rainfall/ML_Data_Preprocessing/output/reanalysis_npz/reanalysis_features_all_standardized_daily.npz"
npz = np.load(npz_path, allow_pickle=True)
print(npz.files)

for i in range(len(npz.files)):
  print(npz.files[i])
  print(npz[npz.files[i]].shape)

print("\nExample patches for single station-date")
print("poloa_UH")
print(npz['patches'][npz['stations'] == 'poloa_UH'][0])
print("aasu_UH")
print(npz['patches'][npz['stations'] == 'aasu_UH'][0])

# print("\nExample patches for single variable")
# #find index of slp variable
# slp_bool_array = npz['variables'] == 'slp'
# slp_index = np.where(slp_bool_array)[0][0]
# print(npz['patches'][0][slp_index])
# print(npz['patches'][1][slp_index])


['patches', 'stations', 'years', 'months', 'variables', 'patch_size', 'days']
patches
(11728, 15, 3, 3)
stations
(11728,)
years
(11728,)
months
(11728,)
variables
(15,)
patch_size
()
days
(11728,)

Example patches for single station-date
poloa_UH


IndexError: index 0 is out of bounds for axis 0 with size 0